info:
  name: openid-configuration
  type: http
  seq: 6

http:
  method: GET
  url: "{{realmUrl}}/.well-known/openid-configuration"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
